# Generated by Django 4.0 on 2021-12-27 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
        ('api', '0004_remove_recipe_tags_alter_amount_ingredient_tagrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trolley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ('user__username', 'recipe__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Favorite_unique_user_recipe_pair'),
        ),
        migrations.AddConstraint(
            model_name='tagrecipe',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='unique_tag_recipe_pair'),
        ),
        migrations.AddField(
            model_name='trolley',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trolley', to='api.recipe'),
        ),
        migrations.AddField(
            model_name='trolley',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trolley', to='users.user'),
        ),
        migrations.AddConstraint(
            model_name='trolley',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Trolley_unique_user_recipe_pair'),
        ),
    ]
