# Generated by Django 4.0 on 2021-12-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_follow_unique_user_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
