# Generated by Django 4.0 on 2021-12-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_recipe_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
