# Generated by Django 4.0 on 2021-12-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_recipe_cooking_time_more_or_equal_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='api.Amount'),
        ),
    ]
