# Generated by Django 4.0 on 2021-12-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_first_name_and_more'),
        ('api', '0009_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Selected',
            new_name='Favorite',
        ),
    ]
