# version: '3.3'
version: '3.8'

volumes:
  media_value:
  static_value:

services:

  frontend:
    build:
      # context: ../frontend
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # - ../frontend/:/app/result_build/
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ./frontend/build:/usr/share/nginx/html/
      # - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      # - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - media_value:/var/html/media/
      - static_value:/var/html/static/
    depends_on:
      - backend

  backend:
    build:
      # context: ../backend
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - media_value:/code/media/
      - static_value:/code/static/