name: Django-test foodgram

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  ## Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r backend/requirements.txt 

    - name: Test with flake8
      run: |
        cd backend/foodgram/
        python -m flake8 

    - name: Test with django tests
      run: |
        cd backend/foodgram/
        python manage.py test
